/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Ranger.gltf -t 
*/

import * as THREE from 'three';
import React, { type JSX } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { type GLTF, SkeletonUtils } from 'three-stdlib';
import { useCharacterAnimation } from '../hooks/useCharacterAnimation';

type ActionName =
  | 'Bow_Draw'
  | 'Bow_Shoot'
  | 'Death'
  | 'Idle'
  | 'Idle_Attacking'
  | 'Idle_Weapon'
  | 'PickUp'
  | 'Punch'
  | 'RecieveHit'
  | 'RecieveHit_2'
  | 'Roll'
  | 'Run'
  | 'Run_Holding'
  | 'Walk';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Cloak: THREE.Mesh;
    ArmGuardL: THREE.Mesh;
    Ranger_Bow: THREE.Mesh;
    ArmGuardR: THREE.Mesh;
    Pouch: THREE.Mesh;
    Ranger: THREE.SkinnedMesh;
    Root: THREE.Bone;
  };
  materials: {
    Ranger_Texture: THREE.MeshBasicMaterial;
    Bow_Texture: THREE.MeshBasicMaterial;
  };
  animations: GLTFAction[];
};

type RangerProps = Omit<JSX.IntrinsicElements['group'], 'id'> & { id: string };

export function Ranger({ id, ...props }: RangerProps) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF('/Ranger.gltf');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useCharacterAnimation(id, actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh
            name="Ranger"
            geometry={nodes.Ranger.geometry}
            material={materials.Ranger_Texture}
            skeleton={nodes.Ranger.skeleton}
            castShadow // Не забываем про тени
            receiveShadow
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/Ranger.gltf');
